[package]
name = "notary"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derive_builder = { workspace = true }
dotenvy = { workspace = true }